"""Security findings models."""

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field


class FindingSeverity(StrEnum):
    """Allowed severities for findings."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Finding(BaseModel):
    """Single security finding generated by analysis modules."""

    model_config = ConfigDict(str_strip_whitespace=True, validate_assignment=True)

    title: str = Field(min_length=1)
    severity: FindingSeverity
    explanation: str = Field(min_length=1)
    evidence: str = Field(min_length=1)
    recommendation: str = Field(min_length=1)
